language: node_js
node_js:
  - "9"
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
env:
  - CXX=g++-4.8
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - zlib1g-dev
      - libpng12-dev
      - libxtst-dev
      - g++-4.8
      - gcc-4.8
